### ISSUE TITLE
callback doesn't always terminate execution when running locally

### ISSUE THREAD

**Issue by jandusek** [twilio-labs/serverless-toolkit#135]
When running a function locally, calling `callback()` doesn't always terminate the execution. When the function is deployed however, `callback()` seems to terminate execution as expected.

Example function that will always throw an error when ran locally, but will run fine when deployed:
```
exports.handler = function (context, event, callback) {
  let response = new Twilio.Response();
  callback(null, response);
  const notReallyUsed = assets['/html/index.html'].open();
  response.appendHeader('Content-Type', 'text/html');
};
```

**Comment by dkundel** [comment]
Yeah this is a known issue atm. We are currently not sandboxing the functions in any way that would allow us to terminate the execution. We should definitely add that though. We are currently discussing the next major version release so this would probably come with that. But it definitely will take some time. Sorry about that.

**Comment by zladuric** [comment]
Just an extra opinion here, but this would _not_ be the behavior I would've expected. If I wanted to end my function after the callback, I want to return myself, explicitly, and not by some magic.

The reason is, what if I have some sort of cleanup logic after the callback? A message to a queue, a log message, a database write?

I understand that I might want to end the result if it succeeds. But then if I depended on something in the callback, I would wrap that part in try/catch block. (And await the result, if the callback can fail asynchronously).

This is how things work in Node (and other JavaScript engines that I know of). Magical exit would definitely break expectations.

Just my humble thoguths on the topic.

**Comment by philnash** [comment]
@zladuric Thanks for your input here. The thing about this is that we are not dealing just with the behaviour of Node.js, but the behaviour of Twilio Functions. [As it says in the documentation](https://www.twilio.com/docs/runtime/functions/invocation#callback-and-asynchronous-limitations):

> It is important to note that when the callback function is invoked, it will terminate all execution of your Function. This includes any asynchronous processes you may have kicked off during during the execution of your handler.
>
> For this reason, if you are using libraries that are natively asynchronous, you need to nest your call to the callback function inside the promise handler.

This issue is necessary so that we can replicate this behaviour in the local version with `twilio-run` so that you don't expect lines after the callback to be run in the deployed environment because they did in the local one.

I hope this makes sense.

**Comment by zladuric** [comment]
Yep, thanks for the in-depth explanation. Allthough I should then probably take my reasoning to the actual Functions thing, not to the twillio-run. But it's not something that I currently use in any case so I'll leave it in your hands.

**Comment by philnash** [comment]
This has been made default for the next version of `twilio-run` in #238.
