### ISSUE TITLE
Remove function

### ISSUE THREAD

**Issue by SpicyPete** [twilio-labs/serverless-toolkit#148]
When I remove a function and re-deploy, the old functions continue to exist on Twilio, and there doesn't seem to be a UI in the Twilio dashboard to remove a function deployed via the new functions API.  
How does one remove a deployed function?

**Comment by dkundel** [comment]
You are correct that when you redeploy with the Function file removed that the Function Resource and previous versions will stick around. It won't be accessible anymore and it's not deployed anymore. But previous versions are still stored by Twilio (not active though). That's on purpose because it's hard to tell for us whether you actually want it gone. The way you can delete it is by deleting it through the API directly or via other Twilio CLI commands.

There might be a couple of steps that you have to do though.

You can only [delete a Function resource](https://www.twilio.com/docs/runtime/functions-assets-api/api/function#delete-a-function-resource) if the there is no [Function Version](https://www.twilio.com/docs/runtime/functions-assets-api/api/function-version) that's currently active in any previous [build](https://www.twilio.com/docs/runtime/functions-assets-api/api/build). And Builds can be active on multiple [Environments](https://www.twilio.com/docs/runtime/functions-assets-api/api/environment).

As a result we don't end up deleting Function resources for you because we could only do that if it wasn't active on any other environment that you have and that behavior might become to unpredictable. Plus it wouldn't allow you to rollback to a previous version anymore in case the things you did were wrong.

The docs I linked you to show the different API commands including how to do them in the Twilio CLI. 

The steps you have to do are:
1. get a list of all Environments
2. get the list of all currently active Builds
3. check the Function Versions that are bundled in any of those Builds
4. check if any of the Functions is associated with the Function resource you are trying to delete
5. change any environments that might have to have new Builds associated that don't contain the Function
6. then you should be able to delete the Function resource.

I hope this helps.
