### ISSUE TITLE
Using --profile creates .env with API key instead of AC SID

### ISSUE THREAD

**Issue by dsmwong** [twilio-labs/serverless-toolkit#213]
running 
`twilio serverless:init --empty --profile MyProject new-service`

creates an .env file with ACCOUNT_SID=SKXXXXXXXXXXXX (API Key rather than MyProject Account SID)

causing an issue when I hit my function call

```
Entered /create-call node version v10.20.1 twilio version 3.55.0

│ ERROR Invalid Account SID
│ 
│ The value for your ACCOUNT_SID in your .env file is not a valid Twilio Account SID. 
│ 
│ It should look like this: ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

500 POST /create-call │ Response Type application/json; charset=utf-8
```

Not sure what's the best way to deal with this - I prefer to use API Key to access, but I'm guessing TwilioClient requires ACxxxxxx to make things work.

**Comment by philnash** [comment]
The Serverless Toolkit prefers to work with Account SID and Auth Tokens to match the behaviour within Twilio Functions. This matters particularly for protected functions, which require the Auth Token to validate incoming requests. The `context.getTwilioClient()` method within a Twilio Function also uses the environment variables `ACCOUNT_SID` and `AUTH_TOKEN`.

There is more explanation of how this came about within the Serverless Toolkit in #163 as well as a plan to tackle fixing it for the future.

In the meantime, the best thing to do is to update your `.env` file to use Account SID and Auth Token instead of API Key and Secret.
