### ISSUE TITLE
Why does serverless:start have weird option documentation?

### ISSUE THREAD

**Issue by NReilingh** [twilio-labs/serverless-toolkit#215]
When I run `twilio serverless:start --help` I get back a lot of options like:

```
  -c, --config=config                  [default: .twilio-functions] Location of 
                                       the config file. Absolute path or 
                                       relative to current working directory 
                                       (cwd)

  -e, --env=env                        Loads .env file, overrides local env 
                                       variables

  -l, --logLevel=logLevel              [default: info] Level of logging 
                                       messages.

  -p, --port=port                      (required) [default: 3000] Override 
                                       default port of 3000

  --assets-folder=assets-folder        Specific folder name to be used for 
                                       static assets

  --cwd=cwd                            Alternative way to define the directory 
                                       to start the server in. Overrides the 
                                       [dir] argument passed.

  --functions-folder=functions-folder  Specific folder name to be used for 
                                       static functions

  --inspect=inspect                    Enables Node.js debugging protocol

  --inspect-brk=inspect-brk            Enables Node.js debugging protocol, stops 
                                       executioin until debugger is attached

  --ngrok=ngrok                        Uses ngrok to create and outfacing url
```

The option name is duplicated as the token for its argument. I find this to be completely unhelpful and confusing in most cases, except in perhaps the case of `--port` and `--logLevel`. The argument should be descriptive of what would actually be passed in there, like `--ngrok=domain`. Perhaps we would even expect to mirror node's documentation, like `--inspect[=[host:]port]` and `--inspect-brk[=[host:]port]`.

Also strange: the typo under ngrok of "and outfacing". I can't find that text anywhere in this repo. Where is it coming from?

This issue is for usability and documentation clarity, but also to investigate whether this is generated documentation beyond our control, or if there is room for improvement.

**Comment by philnash** [comment]
Huh, this is a little weird. From a very quick investigation, it seems that the option name duplication comes from the Twilio CLI rather than `twilio-run` (which is where the `start` command is defined).

If you run

```
npx twilio-run start --help
```

You don't see the duplication, which is different to running

```
twilio serverless:start --help
```

I checked that other core commands in the Twilio CLI do the same, and they do, so this may be something to do with oclif and its settings.

In the meantime, if you want to make any of the command option documentation better (I agree that the ngrok one sounds a bit off) you can find the definitions in the commands directory. The start command, for example, is here: https://github.com/twilio-labs/serverless-toolkit/blob/main/packages/twilio-run/src/commands/start.ts and we really appreciate pull requests.

Thanks!

**Comment by NReilingh** [comment]
Hi, @philnash,

It looks like you were actually responsible for fixing that ngrok typo in this commit: https://github.com/twilio-labs/serverless-toolkit/commit/b78a1f8a40306a254d89e792be47aaa8e1121d53 -- yet the change isn't showing up in the current version of the serverless plugin for twilio-cli:

```
% twilio --version
twilio-cli/2.16.1 darwin-x64 node-v10.23.1
% twilio plugins
@twilio-labs/plugin-serverless 1.8.0
```

Admittedly, I never remember to update plugins for the CLI -- they are omitted from the usual update notifications that the cli itself prints out to your terminal when something new is available from `brew upgrade`. But I just ran `twilio plugins:update` and that's what is showing as the current version.

What's the logic to those version numbers? twilio-run is at 2.8.0, not 1.8.0...

**Comment by philnash** [comment]
I think that's not showing because we've been working towards a new major version which hasn't been released yet.

The serverless plugin is actually made up of a few other Node modules: `twilio-run`, `create-twilio-function` and `@twilio-labs/serverless-api`. So you are seeing the version of the plugin that wraps them all up and makes them available to the Twilio CLI. That is currently at 1.8.0, but if you want to use the absolute latest, you can run `twilio plugins:install @twilio-labs/plugin-serverless@next` and you will get 2.0.0-beta.0 which has some corrections and other fixes. Though it is beta and as we return to work on it, may change before being released as version 2 finally.

**Comment by NReilingh** [comment]
Another weird thing about the option documentation, but from the opposite side: `twilio serverless:start --help` illustrates the `--[no-]live` and `--[no-]logs` pattern for boolean switches which default to true, but on the `twilio-run start --help` side, you just get:

```
  --logs                       Toggles request logging [boolean] [default: true]
  --live                       Always serve from the current functions (no
                               caching)                [boolean] [default: true]
```

This also appears to be code-generated somewhere, since the example switches themselves don't appear in the source file referenced earlier in this issue. I wonder if this behavior comes from an upstream dependency used to build the CLI tools?

**Comment by philnash** [comment]
The commands for `twilio-run` are created by the [`yargs`](https://github.com/yargs/yargs) project, but when they are used by the Twilio CLI as a plugin, they are created by [`oclif`](https://github.com/oclif/oclif). The differences you are see are down to the differences in those projects (I don't think we've customised the output particularly).
