### ISSUE TITLE
Refer not working in Functions

### ISSUE THREAD

**Issue by asfo** [twilio-labs/serverless-toolkit#216]
I have the following code that works locally:
```js
const twilioVoice = new Twilio.twiml.VoiceResponse();

const refer = twilioVoice.refer();
refer.sip(context.SIP_CONNECTION);
callback(null, twilioVoice);
```

But, when I deploy this, I got an issue that `refer` is not a valid function.

Or maybe I did something wrong but since it works in my local, I tough it should in the functions deployed side...

**Comment by philnash** [comment]
This is likely because the default version of the Twilio Node module does not support `refer`.

You can fix this by installing the latest version of `twilio` in your function locally, and then redeploying. This will then use the latest version of `twilio` in your Function and the `refer` function will be supported.

Let me know how you get on with this.

**Comment by asfo** [comment]
> This is likely because the default version of the Twilio Node module does not support `refer`.
> 
> You can fix this by installing the latest version of `twilio` in your function locally, and then redeploying. This will then use the latest version of `twilio` in your Function and the `refer` function will be supported.
> 
> Let me know how you get on with this.

I have the latest version of it (this shows version 2.8.0)
https://www.npmjs.com/package/twilio-run

And I have 2.8.0 installed:
![image](https://user-images.githubusercontent.com/829964/107785093-c8764d80-6d11-11eb-8fc8-06de76127057.png)

And it's supposed that Functions inside the Twilio Cloud should have this supported but it doesn't, so I think the Cloud version is outdated or something...

**Comment by philnash** [comment]
I'm talking about the `twilio` package, not `twilio-run`.

If you navigate to your project and run `npm install twilio` then deploy with `twilio serverless:deploy` you should be fine.

**Comment by asfo** [comment]
I see, based on this I have `twilio@3.54.2` but, how that solves the issue at server-level? I mean, this issue is not happening in my local, I can execute the `refer` method/verb without problems but when I deploy this, I got that error. How is that supposed to help at server level?, when that happens, the `twilio` package inside my proyect is getting updated and the server forces the usage of my local package instead? and the `twilio-run` package use the updated version?

I can't test it right now, so I'm wondering if that is what is going to happen and do it ASAP

**Comment by philnash** [comment]
This is because the Twilio Functions environment has a default version of the `twilio` package, which I believe is 3.29.2 at the moment, though could be older. Because you are not currently specifying a version of the `twilio` package yourself, when you deploy your functions they use the default version and that does not have support for some of the functionality you are using.

When you create a project using the serverless toolkit, the tool `twilio-run` is installed as a devDependency. This allows you to do things like serve functions locally and deploy them. `twilio-run` has an internal dependency on `twilio` and pulls the latest version. So locally, you have the latest version of `twilio` available, but only through a dependency of one of your devDependencies.

So, installing `twilio` as a named dependency within your project will mean it gets installed in the deployed functions runtime and you will have all the functionality of the latest version of the package.

**Comment by asfo** [comment]
Haa I see @philnash thanks!.

Update:
I did the advice and it worked! ...thanks!
