### ISSUE TITLE
New Typescript function won't run (incorrect tsconfig setup)

### ISSUE THREAD

**Issue by daniel-simpson** [twilio-labs/serverless-toolkit#299]
After creating a new function and attempting to start it using the following commands:

```sh
twilio serverless:init myfunctionname --typescript
npm start
```

The Twilio CLI is unable to find any functions to run.  In order to fix, I had to add the `rootDir` setting following line into the tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
+   "rootDir": "src",
    "outDir": "dist",
    "skipLibCheck": true,
    "sourceMap": true
  }
}
```

**Comment by philnash** [comment]
Hey @daniel-simpson, thanks for this report.

I just ran these commands:

```bash
twilio serverless:init myfunctionname --typescript
cd myfunctionname
npm start
```

and the project was compiled and started successfully.

Some questions. Did you `cd` into the new functions project before trying to start it? Was there an error or other output from the command? What OS are you running? And what version of TypeScript did npm install to the project?

Did you run `npm start` or `twilio serverless:start`? I tried both and `npm start` worked, but `twilio serverless:start` did not. This is expected behaviour as `twilio serverless:start` is unaware of TypeScript or other project settings. You would need to run `npm run build` first, then `twilio serverless:start --functions-folder dist/functions --assets-folder dist/assets` to successfully run the project.

**Comment by daniel-simpson** [comment]
Sorry about the delay, haven't had a chance to come back to this.  

From memory, I did exactly the same as the above, but due to the incorrect configuration in tsconfig (maybe something overridden on my machine?) the functions themselves weren't running.

Feel free to close for now, and if I can come up with better repro steps I'll add another comment :) 

Thanks!

**Comment by philnash** [comment]
Hey @daniel-simpson, thanks for getting back to me. Do you mind maybe just running these three commands again to see what happens:

```
twilio serverless:init myfunctionname --typescript
cd myfunctionname
npm start
```

They won't affect anything in your Twilio account and you can delete the directory straight after. I just want to confirm that this either does work or requires the change you made to `tsconfig.json`.

Thanks!

**Comment by daniel-simpson** [comment]
Just ran exactly what you have above, and it all worked perfectly.  Not sure what I was missing last time but my functions definitely came up :) 

![image](https://user-images.githubusercontent.com/4665754/125225201-39964d00-e312-11eb-8fa4-a64b5596f9fc.png)

**Comment by philnash** [comment]
Cool, glad to see it does work! I'll close this for now, but if it doesn't compile for you properly again, do let me know what the circumstances are for it and we'll get it sorted.
