### ISSUE TITLE
Alias "twilio api:serverless:v1:services:remove" to twilio serverless:remove

### ISSUE THREAD

**Issue by deshartman** [twilio-labs/serverless-toolkit#310]
Looking at the Twilio Serverless help, the one item that seems to be missing is to remove a serverless deployment. It is contained in the more generic api service. 

Seems like a handy addition to create new "remove" option that does what the "twilio api:serverless:v1:services:remove" does. Brings it together under the one umbrella.

        twilio serverless:COMMAND
        
        COMMANDS
          serverless:deploy          deploys your local serverless project
          serverless:init            creates a new Twilio Serverless project
          serverless:list            lists services, projects and similar related to your project
          serverless:list-templates  Lists the available Twilio Function templates
          serverless:logs            Print logs from your Twilio Serverless project
          serverless:new             bootstraps a new function in your local project
          serverless:promote         moves an active deployment from one environment to another
          serverless:start           starts a local development environment
          serveless:remove           removes a service from Twilio Functions

**Comment by dkundel** [comment]
Hey @deshartman the reason why we haven't added that functionality yet is because we had no design of providing any other additional functionality at which point we don't implement a single API request primarily because everything under `api:*` is auto-generated meaning it will always be up-to-date with what the API can do while `serverless:*` is handcrafted. That being said I just created #311 and these two proposals might fit well together. Would love to hear your opinion.

**Comment by deshartman** [comment]
Comments left in #311. I think it is a better approach, so we can close this one
