### ISSUE TITLE
twilio:serverless deploy fails in MacOS Ventura

### ISSUE THREAD

**Issue by frvilla** [twilio-labs/serverless-toolkit#411]
After upgrading to MacOS Ventura pre-release, I experienced this issue with twilio command all together which I fixed by adding this line: 
![image](https://user-images.githubusercontent.com/105011261/182641792-a8ff39ca-6eaa-4677-b99a-53719beab128.png)
That fixed the command but twilio serverless:deploy still gives me this error:
`    TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

**Comment by philnash** [comment]
I am currently using MacOS Monterey, so cannot reproduce this. Your issue with the serverless toolkit seems different to the one fixed with the update to `macos-releases`. Are you able to share the file and line number on which that error occurred?

Also, a new version was released very recently, so please do update to the latest and try again.

Thanks!

**Comment by makserik** [comment]
Hi @frvilla are you still seeing this? Please reopen if so.
